<user>
	<userID>0000dave</userID>
	<alias>0000dave</alias>
	<stats>
		<bookmarks>75</bookmarks>
		<tags>126</tags>
	</stats>
	<top10tags>
		<tag>
			<title>design</title>
			<count>19</count>
		</tag>
		<tag>
			<title>webdesign</title>
			<count>13</count>
		</tag>
		<tag>
			<title>art</title>
			<count>11</count>
		</tag>
		<tag>
			<title>blog</title>
			<count>7</count>
		</tag>
		<tag>
			<title>education</title>
			<count>5</count>
		</tag>
		<tag>
			<title>color</title>
			<count>4</count>
		</tag>
		<tag>
			<title>culture</title>
			<count>4</count>
		</tag>
		<tag>
			<title>fonts</title>
			<count>4</count>
		</tag>
		<tag>
			<title>video</title>
			<count>4</count>
		</tag>
		<tag>
			<title>visualization</title>
			<count>4</count>
		</tag>
	</top10tags>
	<allTags>
		<tag>
			<title>3d</title>
			<count>1</count>
		</tag>
		<tag>
			<title>80s</title>
			<count>1</count>
		</tag>
		<tag>
			<title>academia</title>
			<count>1</count>
		</tag>
		<tag>
			<title>action</title>
			<count>1</count>
		</tag>
		<tag>
			<title>adobe</title>
			<count>2</count>
		</tag>
		<tag>
			<title>apple</title>
			<count>1</count>
		</tag>
		<tag>
			<title>art</title>
			<count>11</count>
		</tag>
		<tag>
			<title>assessment</title>
			<count>1</count>
		</tag>
		<tag>
			<title>banksy</title>
			<count>2</count>
		</tag>
		<tag>
			<title>bansky</title>
			<count>1</count>
		</tag>
		<tag>
			<title>blog</title>
			<count>7</count>
		</tag>
		<tag>
			<title>books</title>
			<count>1</count>
		</tag>
		<tag>
			<title>cctv</title>
			<count>1</count>
		</tag>
		<tag>
			<title>cms</title>
			<count>1</count>
		</tag>
		<tag>
			<title>collaboration</title>
			<count>1</count>
		</tag>
		<tag>
			<title>color</title>
			<count>4</count>
		</tag>
		<tag>
			<title>colour</title>
			<count>1</count>
		</tag>
		<tag>
			<title>comedy</title>
			<count>1</count>
		</tag>
		<tag>
			<title>commoncraft</title>
			<count>1</count>
		</tag>
		<tag>
			<title>community</title>
			<count>2</count>
		</tag>
		<tag>
			<title>computer</title>
			<count>1</count>
		</tag>
		<tag>
			<title>corruption</title>
			<count>1</count>
		</tag>
		<tag>
			<title>css</title>
			<count>2</count>
		</tag>
		<tag>
			<title>culture</title>
			<count>4</count>
		</tag>
		<tag>
			<title>cute</title>
			<count>1</count>
		</tag>
		<tag>
			<title>D2L</title>
			<count>1</count>
		</tag>
		<tag>
			<title>dance</title>
			<count>1</count>
		</tag>
		<tag>
			<title>design</title>
			<count>19</count>
		</tag>
		<tag>
			<title>development</title>
			<count>2</count>
		</tag>
		<tag>
			<title>documentary</title>
			<count>1</count>
		</tag>
		<tag>
			<title>drm</title>
			<count>1</count>
		</tag>
		<tag>
			<title>e-learning</title>
			<count>1</count>
		</tag>
		<tag>
			<title>education</title>
			<count>5</count>
		</tag>
		<tag>
			<title>electronic</title>
			<count>2</count>
		</tag>
		<tag>
			<title>english</title>
			<count>1</count>
		</tag>
		<tag>
			<title>facebook</title>
			<count>1</count>
		</tag>
		<tag>
			<title>fail</title>
			<count>1</count>
		</tag>
		<tag>
			<title>font</title>
			<count>1</count>
		</tag>
		<tag>
			<title>fonts</title>
			<count>4</count>
		</tag>
		<tag>
			<title>free</title>
			<count>3</count>
		</tag>
		<tag>
			<title>freeware</title>
			<count>1</count>
		</tag>
		<tag>
			<title>fun</title>
			<count>1</count>
		</tag>
		<tag>
			<title>games</title>
			<count>1</count>
		</tag>
		<tag>
			<title>Generator</title>
			<count>1</count>
		</tag>
		<tag>
			<title>google</title>
			<count>1</count>
		</tag>
		<tag>
			<title>government</title>
			<count>1</count>
		</tag>
		<tag>
			<title>graffiti</title>
			<count>3</count>
		</tag>
		<tag>
			<title>Graphic</title>
			<count>2</count>
		</tag>
		<tag>
			<title>graphics</title>
			<count>3</count>
		</tag>
		<tag>
			<title>grassroots</title>
			<count>1</count>
		</tag>
		<tag>
			<title>hardware,</title>
			<count>1</count>
		</tag>
		<tag>
			<title>HDR</title>
			<count>2</count>
		</tag>
		<tag>
			<title>history</title>
			<count>1</count>
		</tag>
		<tag>
			<title>icons</title>
			<count>1</count>
		</tag>
		<tag>
			<title>ideas</title>
			<count>1</count>
		</tag>
		<tag>
			<title>independent</title>
			<count>1</count>
		</tag>
		<tag>
			<title>information</title>
			<count>1</count>
		</tag>
		<tag>
			<title>inspiration</title>
			<count>3</count>
		</tag>
		<tag>
			<title>interactive</title>
			<count>1</count>
		</tag>
		<tag>
			<title>interesting</title>
			<count>2</count>
		</tag>
		<tag>
			<title>interface</title>
			<count>2</count>
		</tag>
		<tag>
			<title>internet</title>
			<count>2</count>
		</tag>
		<tag>
			<title>itunes</title>
			<count>1</count>
		</tag>
		<tag>
			<title>javascript</title>
			<count>1</count>
		</tag>
		<tag>
			<title>journalism</title>
			<count>2</count>
		</tag>
		<tag>
			<title>law</title>
			<count>1</count>
		</tag>
		<tag>
			<title>learning</title>
			<count>1</count>
		</tag>
		<tag>
			<title>lifehacks</title>
			<count>1</count>
		</tag>
		<tag>
			<title>london</title>
			<count>1</count>
		</tag>
		<tag>
			<title>magiceye</title>
			<count>1</count>
		</tag>
		<tag>
			<title>mario</title>
			<count>1</count>
		</tag>
		<tag>
			<title>math</title>
			<count>1</count>
		</tag>
		<tag>
			<title>media</title>
			<count>3</count>
		</tag>
		<tag>
			<title>media_prank</title>
			<count>2</count>
		</tag>
		<tag>
			<title>media_theory</title>
			<count>2</count>
		</tag>
		<tag>
			<title>microsoft</title>
			<count>1</count>
		</tag>
		<tag>
			<title>moma</title>
			<count>1</count>
		</tag>
		<tag>
			<title>movies</title>
			<count>1</count>
		</tag>
		<tag>
			<title>music</title>
			<count>4</count>
		</tag>
		<tag>
			<title>nature</title>
			<count>1</count>
		</tag>
		<tag>
			<title>nintendo</title>
			<count>1</count>
		</tag>
		<tag>
			<title>opensource</title>
			<count>4</count>
		</tag>
		<tag>
			<title>patterns</title>
			<count>1</count>
		</tag>
		<tag>
			<title>PDF</title>
			<count>1</count>
		</tag>
		<tag>
			<title>photography</title>
			<count>4</count>
		</tag>
		<tag>
			<title>photoshop</title>
			<count>1</count>
		</tag>
		<tag>
			<title>pi</title>
			<count>1</count>
		</tag>
		<tag>
			<title>politics</title>
			<count>2</count>
		</tag>
		<tag>
			<title>presentation</title>
			<count>1</count>
		</tag>
		<tag>
			<title>privacy</title>
			<count>2</count>
		</tag>
		<tag>
			<title>productivity</title>
			<count>2</count>
		</tag>
		<tag>
			<title>programming</title>
			<count>2</count>
		</tag>
		<tag>
			<title>public</title>
			<count>1</count>
		</tag>
		<tag>
			<title>quiz</title>
			<count>1</count>
		</tag>
		<tag>
			<title>remix</title>
			<count>1</count>
		</tag>
		<tag>
			<title>resources</title>
			<count>1</count>
		</tag>
		<tag>
			<title>royksopp</title>
			<count>1</count>
		</tag>
		<tag>
			<title>sand</title>
			<count>1</count>
		</tag>
		<tag>
			<title>science</title>
			<count>2</count>
		</tag>
		<tag>
			<title>simple</title>
			<count>1</count>
		</tag>
		<tag>
			<title>software</title>
			<count>2</count>
		</tag>
		<tag>
			<title>space</title>
			<count>1</count>
		</tag>
		<tag>
			<title>statistics</title>
			<count>3</count>
		</tag>
		<tag>
			<title>sweet</title>
			<count>1</count>
		</tag>
		<tag>
			<title>technology</title>
			<count>3</count>
		</tag>
		<tag>
			<title>TED</title>
			<count>1</count>
		</tag>
		<tag>
			<title>text</title>
			<count>1</count>
		</tag>
		<tag>
			<title>tools</title>
			<count>2</count>
		</tag>
		<tag>
			<title>tutorial</title>
			<count>3</count>
		</tag>
		<tag>
			<title>tutorials</title>
			<count>3</count>
		</tag>
		<tag>
			<title>twitter</title>
			<count>2</count>
		</tag>
		<tag>
			<title>typography</title>
			<count>4</count>
		</tag>
		<tag>
			<title>usability</title>
			<count>1</count>
		</tag>
		<tag>
			<title>video</title>
			<count>4</count>
		</tag>
		<tag>
			<title>visual</title>
			<count>2</count>
		</tag>
		<tag>
			<title>visualization</title>
			<count>4</count>
		</tag>
		<tag>
			<title>web</title>
			<count>1</count>
		</tag>
		<tag>
			<title>web2.0</title>
			<count>4</count>
		</tag>
		<tag>
			<title>webapp</title>
			<count>1</count>
		</tag>
		<tag>
			<title>webdesign</title>
			<count>13</count>
		</tag>
		<tag>
			<title>whiteboard</title>
			<count>2</count>
		</tag>
		<tag>
			<title>wikipedia</title>
			<count>1</count>
		</tag>
		<tag>
			<title>writing</title>
			<count>2</count>
		</tag>
		<tag>
			<title>wwf</title>
			<count>1</count>
		</tag>
		<tag>
			<title>xml</title>
			<count>1</count>
		</tag>
		<tag>
			<title>youtube</title>
			<count>3</count>
		</tag>
	</allTags>
	<bookmarks>
		<bookmark>
			<id>7e7b8bc0e60fb9ec5423c0aafbd0bf9d</id>
			<date>1219291200</date>
			<title>11 Powerful Firefox 3 Add-ons That Can Replace Standalone Applications</title>
			<url>http://www.jasonbartholme.com/11-powerful-firefox-3-add-ons-that-can-replace-standalone-applications/</url>
			<tags>
			</tags>
		</bookmark>
		<bookmark>
			<id>e53ad7455cfdb18a32703d3b16846668</id>
			<date>1219291200</date>
			<title>Visualization Strategies: Text &amp; Documents » Tim Showers - Web Development, Design, and Data Visualization» Blog Archive</title>
			<url>http://www.timshowers.com/2008/08/visualization-strategies-text-documents/</url>
			<tags>
				<tag>
					<title>visualization</title>
				</tag>
				<tag>
					<title>typography</title>
				</tag>
				<tag>
					<title>statistics</title>
				</tag>
				<tag>
					<title>text</title>
				</tag>
				<tag>
					<title>development</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>aaf2aba816e227d75d3f6f9da2da662e</id>
			<date>1215403200</date>
			<title>The Common Craft Store | Common Craft - Explanations In Plain English</title>
			<url>http://www.commoncraft.com/store</url>
			<tags>
				<tag>
					<title>video</title>
				</tag>
				<tag>
					<title>tutorials</title>
				</tag>
				<tag>
					<title>commoncraft</title>
				</tag>
				<tag>
					<title>presentation</title>
				</tag>
				<tag>
					<title>simple</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>b1dddb27dffb759cc04d1a3e0e610801</id>
			<date>1215057600</date>
			<title>DailyTech - YouTube Ordered to Give Complete User Logs to Viacom</title>
			<url>http://www.dailytech.com/YouTube+Ordered+to+Give+Complete+User+Logs+to+Viacom/article12265.htm</url>
			<tags>
				<tag>
					<title>privacy</title>
				</tag>
				<tag>
					<title>google</title>
				</tag>
				<tag>
					<title>corruption</title>
				</tag>
				<tag>
					<title>law</title>
				</tag>
				<tag>
					<title>internet</title>
				</tag>
				<tag>
					<title>youtube</title>
				</tag>
				<tag>
					<title>technology</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>81e93f355c53147a154af293a221ed1d</id>
			<date>1214452800</date>
			<title>James Howard Kunstler dissects suburbia | Video on TED.com</title>
			<url>http://www.ted.com/index.php/talks/james_howard_kunstler_dissects_suburbia.html</url>
			<tags>
				<tag>
					<title>TED</title>
				</tag>
				<tag>
					<title>public</title>
				</tag>
				<tag>
					<title>space</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>9c4cbd1d7c402178b4d142c69bb7ef4c</id>
			<date>1214452800</date>
			<title>Johnny Lee demos Wii Remote hacks | Video on TED.com</title>
			<url>http://www.ted.com/index.php/talks/johnny_lee_demos_wii_remote_hacks.html</url>
			<tags>
				<tag>
					<title>whiteboard</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>bd11ae32a953711ce64d16e810c201a3</id>
			<date>1214020800</date>
			<title>Presidential candidate debates arrive on Twitter » VentureBeat</title>
			<url>http://venturebeat.com/2008/06/20/presidential-candidate-debates-arrive-on-twitter/</url>
			<tags>
				<tag>
					<title>twitter</title>
				</tag>
				<tag>
					<title>web2.0</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>94b0e236d710135a87886599dba9b0e3</id>
			<date>1214020800</date>
			<title>eigenfactor.org - ranking and mapping scientific journals</title>
			<url>http://www.eigenfactor.org/map/maps.htm</url>
			<tags>
				<tag>
					<title>science</title>
				</tag>
				<tag>
					<title>visualization</title>
				</tag>
				<tag>
					<title>graphics</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>b8e0729ac6e9db74f745a7721e74bdbd</id>
			<date>1213848000</date>
			<title>Nvidia 7800 Won’t Work</title>
			<url>http://www.photobasement.com/nvidia-7800-wont-work/</url>
			<tags>
				<tag>
					<title>hardware,</title>
				</tag>
				<tag>
					<title>fail</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>46c71d04b52ed357d97c74c62e5071f4</id>
			<date>1213848000</date>
			<title>The Twitter Hall of Shame: 50 Tweets That Will Echo in History - Inside CRM</title>
			<url>http://www.insidecrm.com/features/twitter-hall-of-shame-061908/</url>
			<tags>
				<tag>
					<title>twitter</title>
				</tag>
				<tag>
					<title>web2.0</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>f30d648babc00ef6dcd08b0810668c3d</id>
			<date>1211860800</date>
			<title>A simple Del.icio.us mashup for D2L using Yahoo Pipes and Feed2JS by ClintLalonde.net</title>
			<url>http://clintlalonde.net/2007/09/11/a-simple-delicious-mashup-for-d2l-using-yahoo-pipes-and-feed2js/</url>
			<tags>
				<tag>
					<title>D2L</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>fcdb7ab409482926ee1b058ae73e8ee7</id>
			<date>1211428800</date>
			<title>YouTube - Alice</title>
			<url>http://www.youtube.com/watch?v=pAwR6w2TgxY</url>
			<tags>
				<tag>
					<title>music</title>
				</tag>
				<tag>
					<title>YouTube</title>
				</tag>
				<tag>
					<title>remix</title>
				</tag>
				<tag>
					<title>video</title>
				</tag>
				<tag>
					<title>electronic</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>8917147624647f5f62d0f03004e6330f</id>
			<date>1211169600</date>
			<title>Writing Multiple Choice Items which Require Comprehension</title>
			<url>http://www.psywww.com/selfquiz/aboutq.htm</url>
			<tags>
				<tag>
					<title>quiz</title>
				</tag>
				<tag>
					<title>assessment</title>
				</tag>
				<tag>
					<title>tutorial</title>
				</tag>
				<tag>
					<title>writing</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>edc7d97aa2353e503ec91b345200b47e</id>
			<date>1211169600</date>
			<title>CTL: Publications: For Your Consideration #8</title>
			<url>http://ctl.unc.edu/fyc8.html</url>
			<tags>
				<tag>
					<title>education</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>bf4b451e4cef764822c4f6d4a1269add</id>
			<date>1210824000</date>
			<title>The Atlantic Online | June 2008 | In the Basement of the Ivory Tower | Professor X</title>
			<url>http://www.theatlantic.com/doc/print/200806/college</url>
			<tags>
				<tag>
					<title>education</title>
				</tag>
				<tag>
					<title>academia</title>
				</tag>
				<tag>
					<title>culture</title>
				</tag>
				<tag>
					<title>english</title>
				</tag>
				<tag>
					<title>writing</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>908f14d1ca826cc0b8a3322fb1297e8d</id>
			<date>1210564800</date>
			<title>FontStruct | Build, Share, Download Fonts</title>
			<url>http://fontstruct.fontshop.com/</url>
			<tags>
				<tag>
					<title>fonts</title>
				</tag>
				<tag>
					<title>Design</title>
				</tag>
				<tag>
					<title>Typography</title>
				</tag>
				<tag>
					<title>font</title>
				</tag>
				<tag>
					<title>Generator</title>
				</tag>
				<tag>
					<title>Free</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>de246e1f624d0c07e075901257869d01</id>
			<date>1210305600</date>
			<title>Bruce Lee’s Top 7 Fundamentals for Getting Your Life in Shape</title>
			<url>http://www.positivityblog.com/index.php/2008/03/07/bruce-lees-top-7-fundamentals-for-getting-your-life-in-shape/</url>
			<tags>
				<tag>
					<title>inspiration</title>
				</tag>
				<tag>
					<title>lifehacks</title>
				</tag>
				<tag>
					<title>productivity</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>94047beee55374abf9e7f560e8e544b9</id>
			<date>1210219200</date>
			<title>http://apina.biz/6580.jpg</title>
			<url>http://apina.biz/6580.jpg</url>
			<tags>
				<tag>
					<title>wwf</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>58f263e50e6c8206a7c69022d7177987</id>
			<date>1210219200</date>
			<title>Team WhiteBoarding with Twiddla - Painless Team Collaboration for the Web</title>
			<url>http://www.twiddla.com/</url>
			<tags>
				<tag>
					<title>collaboration</title>
				</tag>
				<tag>
					<title>whiteboard</title>
				</tag>
				<tag>
					<title>web2.0</title>
				</tag>
				<tag>
					<title>tools</title>
				</tag>
				<tag>
					<title>webapp</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>87aaaae43e600295a8ead94efecd2845</id>
			<date>1210219200</date>
			<title>Each Grain of Sand a Tiny Work of Art | Earth Science | DISCOVER Magazine</title>
			<url>http://discovermagazine.com/photos/01-each-grain-of-sand-a-tiny-work-of-art?dupe</url>
			<tags>
				<tag>
					<title>nature</title>
				</tag>
				<tag>
					<title>Science</title>
				</tag>
				<tag>
					<title>photography</title>
				</tag>
				<tag>
					<title>Art</title>
				</tag>
				<tag>
					<title>sand</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>6ee24f173f434229305a6ea3ad25f32c</id>
			<date>1210219200</date>
			<title>The Cans Festival</title>
			<url>http://www.thecansfestival.com/</url>
			<tags>
				<tag>
					<title>graffiti</title>
				</tag>
				<tag>
					<title>london</title>
				</tag>
				<tag>
					<title>banksy</title>
				</tag>
				<tag>
					<title>art</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>a21f25c3c6ef228f0739a63848744fcd</id>
			<date>1210046400</date>
			<title>Flickr Photo Download: One Nation under CCTV</title>
			<url>http://www.flickr.com/photos/naughton321/2454596198/sizes/m/</url>
			<tags>
				<tag>
					<title>bansky</title>
				</tag>
				<tag>
					<title>cctv</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>9f15211a4e9571171999cb52e9a658b2</id>
			<date>1210046400</date>
			<title>Thermal Reaction: Preschool Politics</title>
			<url>http://thermalreaction.blogspot.com/2008/05/preschool-politics.html</url>
			<tags>
				<tag>
					<title>independent</title>
				</tag>
				<tag>
					<title>media</title>
				</tag>
				<tag>
					<title>cute</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>6d898249b545dcf2491bbb43106df1d4</id>
			<date>1210046400</date>
			<title>5 Sources for Free Computer Technology Education Online -- Education-Portal.com</title>
			<url>http://education-portal.com/articles/5_Sources_for_Free_Computer_Technology_Education_Online.html</url>
			<tags>
				<tag>
					<title>education</title>
				</tag>
				<tag>
					<title>free</title>
				</tag>
				<tag>
					<title>programming</title>
				</tag>
				<tag>
					<title>computer</title>
				</tag>
				<tag>
					<title>e-learning</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>9de7fd1855ea4eed3f25ed5b5f07a795</id>
			<date>1210046400</date>
			<title>The day the music died [dive into mark]</title>
			<url>http://diveintomark.org/archives/2008/05/06/the-day-the-music-died</url>
			<tags>
				<tag>
					<title>drm</title>
				</tag>
				<tag>
					<title>microsoft</title>
				</tag>
				<tag>
					<title>music</title>
				</tag>
				<tag>
					<title>apple</title>
				</tag>
				<tag>
					<title>itunes</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>0dd25b6be1ba8da0599914121408cae1</id>
			<date>1209960000</date>
			<title>bcans1.jpg (JPEG Image, 1000x750 pixels) - Scaled (96%)</title>
			<url>http://www.woostercollective.com/bcans1.jpg</url>
			<tags>
				<tag>
					<title>art</title>
				</tag>
				<tag>
					<title>banksy</title>
				</tag>
				<tag>
					<title>graffiti</title>
				</tag>
				<tag>
					<title>culture</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>014cffcf41a812a695e9a3f6aeb735f9</id>
			<date>1209700800</date>
			<title>Time Management: Where You Find the Time to Spend Online</title>
			<url>http://lifehacker.com/385296/where-you-find-the-time-to-spend-online</url>
			<tags>
				<tag>
					<title>web2.0</title>
				</tag>
				<tag>
					<title>productivity</title>
				</tag>
				<tag>
					<title>internet</title>
				</tag>
				<tag>
					<title>community</title>
				</tag>
				<tag>
					<title>wikipedia</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>a916cce7cbf1a4c9b7028ad4df87c42b</id>
			<date>1209528000</date>
			<title>Abolishing Corporate Personhood, resources and links compiled by Janet Ashford</title>
			<url>http://www.jashford.com/pages/worldcorps.html</url>
			<tags>
				<tag>
					<title>action</title>
				</tag>
				<tag>
					<title>grassroots</title>
				</tag>
				<tag>
					<title>community</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>595767de5f18223bc350684bec6d7aa4</id>
			<date>1209441600</date>
			<title>wjz.com - Police Make Headway In Baltimore Co. Mystery</title>
			<url>http://wjz.com/local/baltimore.county.mystery.2.710503.html</url>
			<tags>
				<tag>
					<title>interesting</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>7ecb2680f28d2612b229992f2af683d8</id>
			<date>1209009600</date>
			<title>30 Alternatives To Adobe Acrobat</title>
			<url>http://www.cartridgesave.co.uk/news/hacks--16/30-alternatives-to-adobe-acrobat--427.html</url>
			<tags>
				<tag>
					<title>PDF</title>
				</tag>
				<tag>
					<title>freeware</title>
				</tag>
				<tag>
					<title>opensource</title>
				</tag>
				<tag>
					<title>adobe</title>
				</tag>
				<tag>
					<title>software</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>09a04b04dff706a41f83203c0c94f76e</id>
			<date>1208318400</date>
			<title>10 Web-Building Resources You Should’ve Already Bookmarked | Six Revisions</title>
			<url>http://sixrevisions.com/resources/10-web-building-resources-you-shouldve-already-bookmarked</url>
			<tags>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>c963c40b03daf85c2bdd758d32254245</id>
			<date>1208232000</date>
			<title>OpenPhotoVR - photo albums with 3D transitions</title>
			<url>http://openphotovr.org/#a69</url>
			<tags>
				<tag>
					<title>photography</title>
				</tag>
				<tag>
					<title>opensource</title>
				</tag>
				<tag>
					<title>3d</title>
				</tag>
				<tag>
					<title>software</title>
				</tag>
				<tag>
					<title>graphics</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>760cacee0c634fde4b516984da161582</id>
			<date>1207713600</date>
			<title>Edward Tufte: Books - The Visual Display of Quantitative Information</title>
			<url>http://www.edwardtufte.com/tufte/books_vdqi</url>
			<tags>
				<tag>
					<title>books</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>visualization</title>
				</tag>
				<tag>
					<title>statistics</title>
				</tag>
				<tag>
					<title>information</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>8e75e1931d95b791618acbe80e681667</id>
			<date>1207627200</date>
			<title>nihilogic: Super Mario in 14kb Javascript</title>
			<url>http://blog.nihilogic.dk/2008/04/super-mario-in-14kb-javascript.html</url>
			<tags>
				<tag>
					<title>javascript</title>
				</tag>
				<tag>
					<title>games</title>
				</tag>
				<tag>
					<title>mario</title>
				</tag>
				<tag>
					<title>programming</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>e85ba7daacfdd04120e2d20fdd52df2b</id>
			<date>1207195200</date>
			<title>Color + Design Blog / COLOURlovers API Documentation and Showcase by COLOURlovers</title>
			<url>http://www.colourlovers.com/blog/2008/04/02/colourlovers-api-documentation-and-showcase/</url>
			<tags>
				<tag>
					<title>colour</title>
				</tag>
				<tag>
					<title>color</title>
				</tag>
				<tag>
					<title>xml</title>
				</tag>
				<tag>
					<title>interface</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
				<tag>
					<title>resources</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>033514b379501f8d74255d021fc32624</id>
			<date>1207108800</date>
			<title>Best Free Documentaries</title>
			<url>http://bestdocumentaries.blogspot.com/</url>
			<tags>
				<tag>
					<title>video</title>
				</tag>
				<tag>
					<title>documentary</title>
				</tag>
				<tag>
					<title>blog</title>
				</tag>
				<tag>
					<title>interesting</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>a3f182e54fa64a1d2000122f87c358e0</id>
			<date>1206936000</date>
			<title>Modder builds SNES portable, Ben Heck approves</title>
			<url>http://www.techeblog.com/index.php/tech-gadget/feature-modder-builds-snes-portable-ben-heck-approves</url>
			<tags>
				<tag>
					<title>nintendo</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>f92b22e479427295ab4a93b0dd788cb7</id>
			<date>1205985600</date>
			<title>I met a butterfly the other day. - random images - moonbuggy</title>
			<url>http://img.moonbuggy.org/i-met-a-butterfly-the-other-day/</url>
			<tags>
				<tag>
					<title>80s</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>02ebd7d6858b2d4723f3d64702948386</id>
			<date>1205726400</date>
			<title>TED: Ideas worth spreading</title>
			<url>http://www.ted.com/index.php/</url>
			<tags>
				<tag>
					<title>ideas</title>
				</tag>
				<tag>
					<title>video</title>
				</tag>
				<tag>
					<title>technology</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>education</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>7b34f8fd920d09c57576b185ee9c6a5e</id>
			<date>1205726400</date>
			<title>kuler</title>
			<url>http://kuler.adobe.com/</url>
			<tags>
				<tag>
					<title>color</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
				<tag>
					<title>tools</title>
				</tag>
				<tag>
					<title>adobe</title>
				</tag>
				<tag>
					<title>graphics</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>40331917a641186bbb4cdcd9a2190292</id>
			<date>1205467200</date>
			<title>Hard N Phirm - Pi</title>
			<url>http://video.google.com/videoplay?docid=924236369691897191</url>
			<tags>
				<tag>
					<title>pi</title>
				</tag>
				<tag>
					<title>math</title>
				</tag>
				<tag>
					<title>comedy</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>7e68c9c6bc9393c1d050b21eff2b3a77</id>
			<date>1205467200</date>
			<title>magic-eye.gif (GIF Image, 652x379 pixels)</title>
			<url>http://vortrack.net/wp-content/uploads/2007/12/magic-eye.gif</url>
			<tags>
				<tag>
					<title>magiceye</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>617f812f0d865c7c0afc2f9695893a26</id>
			<date>1205294400</date>
			<title>MOUNTAIN WINGSUIT</title>
			<url>http://bobandsylvia.com/WINGSUIT.htm</url>
			<tags>
				<tag>
					<title>sweet</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>b2c9982114accf7c1e920a31376bf892</id>
			<date>1205294400</date>
			<title>Design and the Elastic Mind - MoMA</title>
			<url>http://www.moma.org/exhibitions/2008/elasticmind/#</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>art</title>
				</tag>
				<tag>
					<title>Interface</title>
				</tag>
				<tag>
					<title>moma</title>
				</tag>
				<tag>
					<title>interactive</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>3a88b32bc8090d4739c64d235a1614c1</id>
			<date>1205208000</date>
			<title>20 Websites That Made Me A Better Web Developer | Six Revisions : Web Development and Design</title>
			<url>http://sixrevisions.com/resources/20_websites_better_web_developer/</url>
			<tags>
				<tag>
					<title>development</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>web</title>
				</tag>
				<tag>
					<title>css</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>e247aa2ca906dc684b85f5d529ce8fe6</id>
			<date>1205121600</date>
			<title>35 Fantastic HDR Pictures | Monday Inspiration | Smashing Magazine</title>
			<url>http://www.smashingmagazine.com/2008/03/10/35-fantastic-hdr-pictures/</url>
			<tags>
				<tag>
					<title>HDR</title>
				</tag>
				<tag>
					<title>photography</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>2a9a7b2fa385251808ffac7482ab2f25</id>
			<date>1204520400</date>
			<title>Open Font Library Type Casting.</title>
			<url>http://www.openfontlibrary.org/</url>
			<tags>
				<tag>
					<title>fonts</title>
				</tag>
				<tag>
					<title>opensource</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>typography</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>0451dbbc9a86927c1e3ffe244ea4b2a0</id>
			<date>1204520400</date>
			<title>Golden Gate HDR on Flickr - Photo Sharing!</title>
			<url>http://www.flickr.com/photos/vgm8383/2176897085/</url>
			<tags>
				<tag>
					<title>HDR</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>19ea799432123b7124cb6085bae90217</id>
			<date>1204261200</date>
			<title>drupal.org | Community plumbing</title>
			<url>http://drupal.org/</url>
			<tags>
				<tag>
					<title>cms</title>
				</tag>
				<tag>
					<title>opensource</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>cb78898ce61e9358cf70eb2f07223162</id>
			<date>1204174800</date>
			<title>Desiree Palmen - Images - Camouflage 2004</title>
			<url>http://www.desireepalmen.nl/camouflage2.php</url>
			<tags>
				<tag>
					<title>art</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>f14653b9b6bba257b7cb995e1a4441e4</id>
			<date>1204174800</date>
			<title>Wooster Collective</title>
			<url>http://www.woostercollective.com/</url>
			<tags>
				<tag>
					<title>art</title>
				</tag>
				<tag>
					<title>graffiti</title>
				</tag>
				<tag>
					<title>culture</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>Graphic</title>
				</tag>
				<tag>
					<title>media</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>1461115ca593622faaf6d6484699b1a1</id>
			<date>1204174800</date>
			<title>Billboard Liberation Front vs. ATT + NSA - Boing Boing</title>
			<url>http://www.boingboing.net/2008/02/28/billboard-liberation-1.html</url>
			<tags>
				<tag>
					<title>media_prank</title>
				</tag>
				<tag>
					<title>art</title>
				</tag>
				<tag>
					<title>politics</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>224471c819324bc6127769533ea4849d</id>
			<date>1204174800</date>
			<title>YouTube - ElasticIllusion&#039;s Channel</title>
			<url>http://www.youtube.com/user/ElasticIllusion</url>
			<tags>
				<tag>
					<title>youtube</title>
				</tag>
				<tag>
					<title>dance</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>6ed070721a8527d1c7faa7ffe5416ed5</id>
			<date>1204088400</date>
			<title>YouTube - Royksopp - Remind Me</title>
			<url>http://www.youtube.com/watch?v=lBvaHZIrt0o</url>
			<tags>
				<tag>
					<title>music</title>
				</tag>
				<tag>
					<title>royksopp</title>
				</tag>
				<tag>
					<title>visual</title>
				</tag>
				<tag>
					<title>art</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>0e755fd5270c51aa0cd0cafbd994a61f</id>
			<date>1204088400</date>
			<title>McSweeney&#039;s Internet Tendency: A Convergence of Convergences: A Contest.</title>
			<url>http://www.mcsweeneys.net/books/everythingthatrises.contest2.html</url>
			<tags>
				<tag>
					<title>art</title>
				</tag>
				<tag>
					<title>inspiration</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>visual</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>7879a193922b0ffaaee4a122f11fabf3</id>
			<date>1204002000</date>
			<title>No Commercial Potential</title>
			<url>http://nocommercialpotential.net/</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>photography</title>
				</tag>
				<tag>
					<title>art</title>
				</tag>
				<tag>
					<title>inspiration</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>563dff08c131932ce6d64eea27af6e0a</id>
			<date>1204002000</date>
			<title>The Ebb and Flow of Movies: Box Office Receipts 1986 - 2007 - The New York Times</title>
			<url>http://www.nytimes.com/interactive/2008/02/23/movies/20080223_REVENUE_GRAPHIC.html?unomas</url>
			<tags>
				<tag>
					<title>movies</title>
				</tag>
				<tag>
					<title>visualization</title>
				</tag>
				<tag>
					<title>statistics</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>47427d7a75cb000d58b3d2d92e0031f8</id>
			<date>1203656400</date>
			<title>Powerful CSS-Techniques For Effective Coding | CSS | Smashing Magazine</title>
			<url>http://www.smashingmagazine.com/2008/02/21/powerful-css-techniques-for-effective-coding/</url>
			<tags>
				<tag>
					<title>css</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>aced302e45faa3b740cf0b816601fe74</id>
			<date>1203656400</date>
			<title>AlterNet: Democracy and Elections: When Change Is Not Enough: Seven Steps to Revolution</title>
			<url>http://www.alternet.org/democracy/77498/?page=entire</url>
			<tags>
				<tag>
					<title>politics</title>
				</tag>
				<tag>
					<title>history</title>
				</tag>
				<tag>
					<title>government</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>137bdef3cf7d3c96255000c89215afbc</id>
			<date>1203483600</date>
			<title>Table of Contents | The Elements of Typographic Style Applied to the Web</title>
			<url>http://webtypography.net/toc/</url>
			<tags>
				<tag>
					<title>tutorial</title>
				</tag>
				<tag>
					<title>fonts</title>
				</tag>
				<tag>
					<title>blog</title>
				</tag>
				<tag>
					<title>typography</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>f87e3d8628a2510b35be7306e68e6b7b</id>
			<date>1203483600</date>
			<title>The Stingy Scholar</title>
			<url>http://stingyscholar.blogspot.com/</url>
			<tags>
				<tag>
					<title>education</title>
				</tag>
				<tag>
					<title>learning</title>
				</tag>
				<tag>
					<title>free</title>
				</tag>
				<tag>
					<title>blog</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>07bee35d3dbf545baebd55fa0c63b2a0</id>
			<date>1203483600</date>
			<title>Deus Ex Malcontent</title>
			<url>http://www.deusexmalcontent.com/</url>
			<tags>
				<tag>
					<title>blog</title>
				</tag>
				<tag>
					<title>journalism</title>
				</tag>
				<tag>
					<title>media</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>3d86abdadfb6ba0599d5dc09febe8efd</id>
			<date>1203397200</date>
			<title>Electronic Music</title>
			<url>http://analogik.com/</url>
			<tags>
				<tag>
					<title>music</title>
				</tag>
				<tag>
					<title>electronic</title>
				</tag>
				<tag>
					<title>culture</title>
				</tag>
				<tag>
					<title>technology</title>
				</tag>
				<tag>
					<title>art</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>7137984672d8cc9e987efbf9f002d3b5</id>
			<date>1203397200</date>
			<title>Dingbats Roundup: 16 Incredibly Detailed, Useful (and free) Dingbat Fonts | BittBox</title>
			<url>http://www.bittbox.com/fonts/dingbats-roundup-16-incredibly-detailed-useful-and-free-dingbat-fonts/</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>fonts</title>
				</tag>
				<tag>
					<title>icons</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>9d5b95b25e5f9ef7d45cdd3cad6792bc</id>
			<date>1203310800</date>
			<title>Torontoist: The Ones That Mother Gives You</title>
			<url>http://torontoist.com/2008/02/the_ones_that_m.php?</url>
			<tags>
				<tag>
					<title>media_prank</title>
				</tag>
				<tag>
					<title>media_theory</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>4595080434252d0faabee52c79287e17</id>
			<date>1203051600</date>
			<title>Media Workers Against the War » Blog Archive » Nick Davies: How “flat earth” news is killing journalism</title>
			<url>http://www.mwaw.net/2007/12/08/davies/</url>
			<tags>
				<tag>
					<title>journalism</title>
				</tag>
				<tag>
					<title>media_theory</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>7bc54dd15a53635e491ce8d35b6f9688</id>
			<date>1202878800</date>
			<title>www.dontclick.it</title>
			<url>http://www.dontclick.it/</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>usability</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>47abe04ff1533c68fc60345e5ca24e09</id>
			<date>1202878800</date>
			<title>With friends like these ... Tom Hodgkinson on the politics of the people behind Facebook | Technology | The Guardian</title>
			<url>http://www.guardian.co.uk/technology/2008/jan/14/facebook</url>
			<tags>
				<tag>
					<title>facebook</title>
				</tag>
				<tag>
					<title>privacy</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>c39de77808cf561194053ea0f86f7dcc</id>
			<date>1202878800</date>
			<title>ze&#039;s page :: zefrank.com</title>
			<url>http://www.zefrank.com/</url>
			<tags>
				<tag>
					<title>blog</title>
				</tag>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>fun</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>15a88a100d77d8e53b98d465cb96b793</id>
			<date>1202878800</date>
			<title>PSDTuts - Photoshop Tutorials and Links - Spoonfed Photoshop Tutorials</title>
			<url>http://psdtuts.com/</url>
			<tags>
				<tag>
					<title>photoshop</title>
				</tag>
				<tag>
					<title>tutorials</title>
				</tag>
				<tag>
					<title>blog</title>
				</tag>
				<tag>
					<title>tutorial</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>048dac5f9d1d8bad9135f9e0135c9093</id>
			<date>1202878800</date>
			<title>swissmiss</title>
			<url>http://swissmiss.typepad.com/</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
				<tag>
					<title>color</title>
				</tag>
				<tag>
					<title>blog</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>e31d7810d8d790947430d420a2b60fd7</id>
			<date>1202878800</date>
			<title>Home: AIGA</title>
			<url>http://www.aiga.org/</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
				<tag>
					<title>Graphic</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>b3242f0e658692a02f6458c77da1fa42</id>
			<date>1202878800</date>
			<title>Illustrator Tutorials, Illustrator CS Tutorials, Illustrator CS2 Tutorials, Illustrator CS3 Tutorials, Illustrator Tutorial</title>
			<url>http://www.designertoday.com/Tutorials/Illustrator.aspx</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
				<tag>
					<title>tutorials</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>ed660189ea22d2b9cd51395405b4d933</id>
			<date>1202878800</date>
			<title>101 Design Patterns &amp; Tips</title>
			<url>http://sourcemaking.com/design-patterns-and-tips</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>patterns</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
		<bookmark>
			<id>88278dbc98e58c2bede0c88dc7e74678</id>
			<date>1202878800</date>
			<title>COLOURlovers :: Color Trends + Palettes</title>
			<url>http://www.colourlovers.com/</url>
			<tags>
				<tag>
					<title>design</title>
				</tag>
				<tag>
					<title>color</title>
				</tag>
				<tag>
					<title>webdesign</title>
				</tag>
			</tags>
		</bookmark>
	</bookmarks>
</user>